# | Formato | MKV | MP4 | WebM | M4A | OGG | Archivo |
# | ------- | --- | --- | ---- | --- | --- | ------- |
# | AV1     |  ✓  |  ✓  |  ✓   |     |     |         |
# | H.264   |  ✓  |  ✓  |      |     |     |         |
# | H.265   |  ✓  |  ✓  |      |     |     |         |
# | AAC     |  ✓  |  ✓  |      |  ✓  |     |         |
# | E-AC-3  |  ✓  |  ✓  |      |     |     |         |
# | Opus    |  ✓  |     |  ✓   |     |  ✓  |         |
# | SRT     |  ✓  |  ✓  |      |     |     |    ✓    |
# | ASS     |  ✓  |     |      |     |     |    ✓    |

[encode]
video_codec = "h265"
video_preset = "slow"
video_crf = 24
audio_codec = "aac"
audio_bit_rate = "128k"

[default_containers]
animated_image = ".gif"
audio_track = ".m4a"
image = ".jpg"
media = ".mp4"
subtitles = ".srt"

[app]
language = "system"
stall_timeout = 60
